### ISSUE TITLE
Document usage and benchmarking

### ISSUE THREAD

**Issue by lemire** [wrandelshofer/FastDoubleParser#1]
👍 

Can you document how one would run the benchmarks and how one would use the code as an external library?

**Comment by wrandelshofer** [comment]
I have done this now in commit 061fd3e881d7b955948567fef6a9ea62e91594c9 .

**Comment by wrandelshofer** [comment]
I have now added a separate benchmarking class and I have added step by step instructions to the readme. A working version is in commit 569370c5d5e272b67121a40fc5a07e98c42d1aff .

**Comment by wrandelshofer** [comment]
I have now - again - updated the benchmarking class. The results are now comparable to the ones that are shown in the readme of fast_double_parser. In these benchmarks, the speedup is about factor 4.
The revision number is de1fb25bf6d46506a00e31212af49525356e02cf .
