### ISSUE TITLE
float parser

### ISSUE THREAD

**Issue by pjfanning** [wrandelshofer/FastDoubleParser#14]
Hi - thanks for all the great work on the double parser. I've been experimenting with it for possible inclusion in jackson-core.

Parsing floats using the double parser is also much faster than using Float.parseFloat but unfortunately casting doubles to floats can often give you different result from plain Float.parseFloat.

Would it be possible to consider also supporting a dedicated float parser?

An example is 7.006492321624086e-46 which Float.parseFloat returns as 1.4E-45 but using FastDoubleParser:

```
        double dbl = FastDoubleParser.parseDouble("7.006492321624086e-46");
        System.out.println("double=" + dbl); //7.006492321624085E-46
        System.out.println("float=" + (float)dbl); //0.0
```

**Comment by lemire** [comment]
Note that the C# equivalent has such functions (`float` support). See https://github.com/CarlVerret/csFastFloat

**Comment by wrandelshofer** [comment]
I have now refactord the code a bit, and added a new class FastFloatParser.

It should do now what you want. 😅

```
% jshell --module-path out --add-modules ch.randelshofer.fastdoubleparser
|  Welcome to JShell -- Version 18.0.1
|  For an introduction type: /help intro

jshell> import ch.randelshofer.fastdoubleparser.*

jshell> FastFloatParser.parseFloat("7.006492321624086e-46")
$2 ==> 1.4E-45

jshell> 

```

**Comment by pjfanning** [comment]
Thanks @wrandelshofer - I'll try it out over next few days

**Comment by pjfanning** [comment]
I'll close this - so far, looks good to me - thanks
