### ISSUE TITLE
SWAR routines accept invalid non-digit chars/bytes

### ISSUE THREAD

**Issue by plokhotnyuk** [wrandelshofer/FastDoubleParser#16]
https://github.com/wrandelshofer/FastDoubleParser/blob/0903817a765b25e654f02a5a9d4f1476c98a80c9/src/main/java/ch.randelshofer.fastdoubleparser/ch/randelshofer/fastdoubleparser/FastDoubleSimd.java#L117

Use `0x76` instead of `0x46` byte for detection  of invalid digits in "numbers" like `1X345678`.

**Comment by wrandelshofer** [comment]
I tried with all char values from [0, 65535] and it only matched the characters ['0','9']. 
Can you provide an invalid input, that this method accepts?

**Comment by wrandelshofer** [comment]
Ups, I tried with FastDoubleParser.parseDouble(String) which does not use this method. 
Trying again and reporting back here.

**Comment by plokhotnyuk** [comment]
Ups, sorry... I missed that `value` and `val` have different values.

**Comment by lemire** [comment]
This function is definitively correct, at least in principle. I use it all over the place.

You can test it out in Python...

```Python
value = 0
s = "1X345678"
for i in range(len(s)):
    value <<= 8
    value += ord(s[len(s)-1-i])
print(hex(value))
val = value - 0x3030303030303030
det = ((value + 0x4646464646464646) | val) & 0x8080808080808080
print(det)
```
