### ISSUE TITLE
Publish 0.5.2 to maven central

### ISSUE THREAD

**Issue by devinrsmith** [wrandelshofer/FastDoubleParser#29]
Is it possible to publish the 0.5.2 release to maven central?

Thanks for the great project!

**Comment by wrandelshofer** [comment]
Oops. I forgot to change the version number in the POM file, when I submitted it to maven central. 
Apparently my submission got silently discarded.

I have resubmitted it now. Please try retrieving it again.

**Comment by devinrsmith** [comment]
Great, thanks, I see the artifacts :)
