### ISSUE TITLE
Integrating it as the default parser in openjdk

### ISSUE THREAD

**Issue by LifeIsStrange** [wrandelshofer/FastDoubleParser#3]
Hi,
I truly think that https://arxiv.org/abs/2101.11408 is a breakthrough in computer science and that the world would benefit from such parser to be used by default in openjdk (as it is for Go).
(I wonder if an even faster parser couldn't be achieved using jsoniter-scala optimization techniques in addition to Lemire's https://github.com/FasterXML/jackson-core/issues/577 ).

**Comment by wrandelshofer** [comment]
Integration into other projects is out of scope for me.

At this stage, the code that extracts the digits of the mantissa and of the exponent from the String is incomplete - it does not handle all cases that Double.parseDouble handles. 
Also this particular code is very performance sensitive. I need to look again at Lemires original implementation.

**Comment by wrandelshofer** [comment]
So, I am closing this issue with: "Won't do, because I do not have the resources to integrate this into openjdk".
