### ISSUE TITLE
Is this a mistake with hex float parsing?

### ISSUE THREAD

**Issue by tommyettinger** [wrandelshofer/FastDoubleParser#36]
In this section of FastFloatMath, it checks the significand against a 53-bit number (as if it were testing to see if it is an exactly representable double), but then casts to float, despite the comments repeatedly referring to the code as using doubles. I think the cast to float should probably be a cast to double (and `d` should be a double), but I'm not familiar with the code.

https://github.com/wrandelshofer/FastDoubleParser/blob/c7b1162c2c0c2d57b28db1aa14631c3101179778/fastdoubleparser-dev/src/main/java/ch.randelshofer.fastdoubleparser/ch/randelshofer/fastdoubleparser/FastFloatMath.java#L324-L334

**Comment by wrandelshofer** [comment]
Yes, the code and the comments in the code are rubbish. 

I think, all the concerns about rounding are wrong. 
We don't need the if-statement in line 324 at all, if we change line 327 into

float d = Math.abs((float) significand);
