### ISSUE TITLE
Incorrect maven command sequence

### ISSUE THREAD

**Issue by ChenZhongPu** [wrandelshofer/FastDoubleParser#37]
The test can be done with `javac` and `java` directly, but it does NOT work as expected with `maven`.

After `mvn clean package`, the command below raises an error "Error: Could not find or load main class ch.randelshofer.fastdoubleparserdemo.Main in module ch.randelshofer.fastdoubleparserdemo":

```sh
java -XX:CompileCommand=inline,java/lang/String.charAt -p fastdoubleparser/target:fastdoubleparserdemo/target -m ch.randelshofer.fastdoubleparserdemo/ch.randelshofer.fastdoubleparserdemo.Main --markdown
```
I checked the `jar`s inside `fastdoubleparser/target` and `fastdoubleparserdemo/target`, and found that they contains nothing but a `META-INF` folder!

```sh
jar xvf fastdoubleparser-0.7.0.jar
  created: META-INF/
 inflated: META-INF/MANIFEST.MF
```

So, the maven command cannot produce correct jar, and I think it is caused by incorrect Maven project structures and POM configurations. BTW, I think the current *multi-release jar* here is a little overkill.

**Comment by wrandelshofer** [comment]
Can you please try the following command sequence instead? That is what I use for building the project.

```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home
mvn clean install
```

**Comment by wrandelshofer** [comment]
I have recently reduced the size of the multi-release.jar. It is now about 4-times smaller than before.

**Comment by ChenZhongPu** [comment]
> Can you please try the following command sequence instead? That is what I use for building the project.
> 
> ```
> export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home
> mvn clean install
> ```

`mvn clean install` itself work well, in my computer, I added `-Dgpg.skip=true` flag to skip signing. Then the installed package is found in `.m2` folder. However, the generated jar also contains nothing but a `META-INF` folder.

```sh
pwd
/home/zhongpu/.m2/repository/ch/randelshofer/fastdoubleparser/0.7.0

ll -h
total 112K
-rw-r--r-- 1 zhongpu zhongpu  481 Mar  2 14:32 fastdoubleparser-0.7.0.jar
-rw-r--r-- 1 zhongpu zhongpu 1.7K Mar  2 14:32 fastdoubleparser-0.7.0.pom
-rw-r--r-- 1 zhongpu zhongpu  93K Mar  2 14:32 fastdoubleparser-0.7.0-sources.jar
drwxr-xr-x 2 zhongpu zhongpu 4.0K Feb 26 18:31 META-INF
-rw-r--r-- 1 zhongpu zhongpu  228 Mar  2 14:32 _remote.repositories

jar xvf fastdoubleparser-0.7.0.jar
  created: META-INF/
 inflated: META-INF/MANIFEST.MF
```
Notice that the jar is strangely small.

The Java I am using is: `OpenJDK Runtime Environment (build 20-ea+34-2340)`.

**Comment by ChenZhongPu** [comment]
The issue can be fixed to use a higher version of  `maven`. I was using `3.2.5`, but when I switch to `3.8.7`, everything goes fine.

I think the README should specify the minimum (recommend) version of maven to build it from source.

**Comment by wrandelshofer** [comment]
The README file states the required version of Maven here:
https://github.com/wrandelshofer/FastDoubleParser/blob/52475f31fe7573815532d78ca6262c186afd8272/README.md?plain=1#L252

Did you miss it, because the version number was mentioned in the title? 
Should we state the requirements in a bulleted list instead?
