### ISSUE TITLE
porting FastFloatParser

### ISSUE THREAD

**Issue by LifeIsStrange** [wrandelshofer/FastDoubleParser#4]
https://github.com/fastfloat/fast_float
is it on your roadmap ? :)

**Comment by lemire** [comment]
@LifeIsStrange I think you mean specifically 'float' (32 bits) support. Right ?

**Comment by LifeIsStrange** [comment]
correct :)

**Comment by wrandelshofer** [comment]
No, I only need 'double' (32 bits) support.

**Comment by lemire** [comment]
@wrandelshofer Would you invite a pull request on this topic ?

Once you have 64-bit doubles, it is not hard to get 32-bit floats.

**Comment by wrandelshofer** [comment]
Of course. Pull requests are welcome.

**Comment by wrandelshofer** [comment]
So, my resolution to this issue is "Won't do, but pull requests are very welcome".
