### ISSUE TITLE
Document which code signing keys will be used for published artifacts. 

### ISSUE THREAD

**Issue by yogurtearl** [wrandelshofer/FastDoubleParser#41]
Looks like artifacts are being signed with this key: 
https://keyserver.ubuntu.com/pks/lookup?search=6ead752b3e2b38e8e2236d7ba9321edaa5cb3202&fingerprint=on&op=index

If that is the correct key can you add a section to the readme confirming that is the key that is expected to be used for code signing on the artifacts released from this repo? Thanks. :) 

See examples of other libs that provide docs for the code signing key used are here: 

- https://dist.apache.org/repos/dist/release/logging/KEYS
- https://square.github.io/okhttp/security/security/#verifying-artifacts

**Comment by wrandelshofer** [comment]
I have now committed the following file:
https://github.com/wrandelshofer/FastDoubleParser/blob/85a7d65cd25878a9ac243fabb703e56e7d8d7c07/KEYS

hth

**Comment by yogurtearl** [comment]
Thanks!
