### ISSUE TITLE
issue with module-info classes in v0.9.0 release

### ISSUE THREAD

**Issue by pjfanning** [wrandelshofer/FastDoubleParser#42]
There are multiple module-info classes in the v0.9.0 jar. In v0.8.0, there was just the versions/9/module-info.class.

In v0.9.0, there are module-info.class fils in all the versions dirs.

This is causing https://github.com/FasterXML/jackson-core/issues/1027

Would it be possible to get some background on the v0.9.0 changes, so that I can work out what to do with the jackson-core issues?

**Comment by wrandelshofer** [comment]
In prior releases, instead of being explicitly modular, we only had an `Automatic-Module-Name` in the META-INF/MANIFEST.MF file. Now we have proper module-info.class.

**Comment by wrandelshofer** [comment]
% unzip -v fastdoubleparser-0.9.0.jar | grep module-info
     255  Defl:N      179  30% 04-30-2023 05:00 888d9237  META-INF/versions/11/module-info.class
     255  Defl:N      179  30% 04-30-2023 05:00 a6603a18  META-INF/versions/17/module-info.class
     328  Defl:N      191  42% 04-30-2023 05:00 8a1769af  META-INF/versions/19/module-info.class

They should all be identical. So, including a module-info.class for versions/11 should have been sufficient. I don't know why the one for versions/19 is larger (?)

**Comment by pjfanning** [comment]
Thanks, we probably just need to exclude these files from jackson-core.
