### ISSUE TITLE
Double.parseDouble("0e555") != FastDoubleParser.parseDouble("0e555")

### ISSUE THREAD

**Issue by fmeum** [wrandelshofer/FastDoubleParser#6]
`Double.parseDouble` and `FastDoubleParser.parseDouble` return different results for the string `"0e555"`:

```
Double.parseDouble("0e555"): 0.0
FastDoubleParser.parseDouble("0e555"): Infinity
```

Edit: I believe that is caused by the special case at https://github.com/wrandelshofer/FastDoubleParser/blob/daa23920cbfe71b7c545291283b44b136d9a991d/src/ch/randelshofer/math/FastDoubleParser.java#L1089, which does not handle the even more special case of the mantissa being 0.

**Comment by wrandelshofer** [comment]
Thank you very much. I made a fix in revision d8c9aa0e818e1b64fd9d6a22df15dc4a1c074eb2 .
