### ISSUE TITLE
9007199254740992.e-256 will not parsed

### ISSUE THREAD

**Issue by lemire** [wrandelshofer/FastDoubleParser#8]
It appears that wrandelshofer/FastDoubleParser might be tied to  https://github.com/lemire/fast_double_parser which is based on RFC 7159 (JSON standard). This means that strings such as 9007199254740992.e-256 which are not valid in JSON will not parse.

I really recommend you follow more closely the approach in https://github.com/fastfloat/fast_float if you mean to solve the general float parsing problem.

**Comment by wrandelshofer** [comment]
Oh, thank you for the pointer! I have indeed not yet looked at the grammar that fast_double_parser supports.

My idea for this project, is to provide an API that supports the same grammar as Double.valueOf in Java. As described here:
https://download.java.net/java/early_access/jdk16/docs/api/java.base/java/lang/Double.html#valueOf(java.lang.String)

I am planning to implement other frontends in *other* projects. 
I currently have the need for the following grammars:

- The doubleRep production from XML Schema 1.1. https://www.w3.org/TR/xmlschema11-2/#double
- The number-token production from CSS Syntax Level 3. https://www.w3.org/TR/css-syntax-3/#number-token-diagram

**Comment by wrandelshofer** [comment]
This is fixed now in 3be81313a296a725b0b72f0a6de42fb95d59c1e0 .
