### ISSUE TITLE
Using commas as decimal separator?

### ISSUE THREAD

**Issue by Jolanrensen** [wrandelshofer/FastDoubleParser#82]
Hi! I was wondering when integrating this library into our own, do you support different locales?

Different countries have lots of different notations for large numbers:
- 100.123,12
- 100,123.12
- 100 123.12
- https://en.m.wikipedia.org/wiki/Decimal_separator

Fast_float seems to have the function from_chars_advanced for this:
https://github.com/fastfloat/fast_float?tab=readme-ov-file#advanced-options--using-commas-as-decimal-separator-json-and-fortran
however, I wasn't able to find something similar in this library.

**Comment by wrandelshofer** [comment]
The parsers are currently designed for numbers in the Java Syntax and the JSON Syntax. 
These are the formats that are often used for bulk data interchange.

I think, parsing numbers in different locales can be very complex. 

How do you currently parse numbers in your library? Do you use DecimalFormat patterns?
https://docs.oracle.com/en/java/javase/23/docs/api/java.base/java/text/DecimalFormat.html#patterns

**Comment by Jolanrensen** [comment]
@wrandelshofer Exactly, we use `NumberFormat.parse`, which uses `DecimalFormat` under the hood. The place where we most often come across `,` in number is in CSV or Excel files, which are often locale-dependent.

I made a little converter which, based on the source locale, replaces the decimal symbols in source locale's `DecimalFormatSymbols` with those defined in `Locale.ROOT`. That way we can still use FastDoubleParser. Though, this is very hacky and can break easily for more complicated locales.

**Comment by wrandelshofer** [comment]
I think, ideally, we should have a drop-in replacement for DecimalFormat, that works with the same API. 
I need to take a look at this first. I don't know how complex it is.

**Comment by Jolanrensen** [comment]
It might also be possible to follow R here: https://readr.tidyverse.org/articles/locales.html#numbers

The way I understand their `parse_double` function is that the main option is `decimal_mark`. It defaults to "." and all other grouping marks are ignored. If you set it to ",", it assumes "." to be a grouping mark, so it's ignored too.

**Comment by wrandelshofer** [comment]
I am currently leaning towards following the DecimalFormat API.

This allows to use a DecimalFormat instance for the slow path of the parser. This saves a lot of time for the implementation.

Also. In the case that someone discovers an error in our implementation, they can quickly replace it with DecimalFormat until we have fixed it.

@Jolanrensen
I think, DecimalFormat treats an unknown character as the end of its input. 
For example: given grouping separator = `'`, decimal separator = `.`, input string = `1'000,000.30`, parse position = `0`
we get the Long value `1000` and parse position = `5` as the result.

**Comment by Jolanrensen** [comment]
@wrandelshofer I think it does too.
It can also cause some issues though. For instance when you parse a String containing spaces instead of NBSP with the French locale. It looks the same, but if you use the space, the parser will fail. Same with using the wrong minus sign in Estonian. It may be nice to fall back on the "default" locale if the given one fails parsing the input. wdyt?

**Comment by wrandelshofer** [comment]
Well, if you need features that are not supported by DecimalFormat, we need to implement the slow path of the parser by ourselves.

I have yanked that code some time ago. It was complex and may thus be a source of bugs.
I can resurrect that code. If you are willing to take the risk.

How should the API look like?

```java
public class FormattableDoubleParser {
   public FormattableDoubleParser(NumberFormatSymbols symbols);
   public double parse(String) throws NumberFormatException;
}

public record NumberFormatSymbols(
  Set<Character> decimalSeparator,
  Set<Character> groupingSeparator,
  Set<Character> exponentSeparator,
  Set<Character> minusSign,
  Set<Character> plusSign,
  Set<String> infinity,
  Set<String> nan
) {}
```

**Comment by wrandelshofer** [comment]
Um, I think we also need to define a grammar? 

The grammars that we currently support are very restrictive.
I guess, you are looking for a grammar that is lenient, so that the parser can be used to read most formats.

How should the grammar look like?

I would like to use the grammar for [JavaDoubleParser](https://github.com/wrandelshofer/FastDoubleParser/blob/77e838ad797305b4056beb76292236c80b2a2568/fastdoubleparser-dev/src/main/java/ch.randelshofer.fastdoubleparser/ch/randelshofer/fastdoubleparser/JavaDoubleParser.java#L19-L130) as a guideline. 

- We have configurable Sets for the separators.
- Hexadecimal and the float type suffixes are not needed.
- The sign can be at the beginnign or at the end.
- Do we need to support currency symbols? - I am leaving them out for now.

Draft grammar:

```
LenientFloatingPointLiteral:
  [Sign] NaN
  [Sign] Infinity
  [Sign] DecimalFloatingPointLiteral
  NaN [Sign]
  Infinity [Sign]
  DecimalFloatingPointLiteral [Sign]
  

DecimalFloatingPointLiteral:
  DecSignificand [DecExponent]

DecSignificand:
  IntegerPart DecimalSeparator [FractionPart]
  DecimalSeparator FractionPart 
  IntegerPart
  
IntegerPart:
  GroupedDigits

FractionPart:
  Digits
  
DecimalSeparator:
  (one of decimalSeparator) 

DecExponent:
  ExponentIndicator [Sign] Digits

ExponentIndicator:
  (one of exponentSeparator)

Sign:
  (one of minusSign)
  (one of plusSign)

Digits:
  Digit {Digit}

GroupedDigits:
  DigitOrGrouping {DigitOurGrouping}

DigitOrGrouping:
  Digit
  Grouping
  
Digit:
  (one of)
  0 1 2 3 4 5 6 7 8 9

Grouping:
  (one of groupingSeparator)
  
NaN:
  (one of nan)    

Infinity:
  (one of infinity)    
```

**Comment by wrandelshofer** [comment]
Lets call the parser `LenientDoubleParser`.

And - for convenience - add a constructor with the Java DecimalFormatSymbols.

Do all decimal digit sets in Unicode start with a zero character followed by the digits 1 to 9? 
If yes, we can easily support multiple digit sets. All we need to know is the code point of the zero character.


```java
public class LenientDoubleParser {
   public LenientDoubleParser(NumberFormatSymbols symbols);
   public LenientDoubleParser(java.text.DecimalFormatSymbols symbols);
   public double parse(String) throws NumberFormatException;
}

public record NumberFormatSymbols(
  Set<Character> decimalSeparator,
  Set<Character> groupingSeparator,
  Set<Character> exponentSeparator,
  Set<Character> minusSign,
  Set<Character> plusSign,
  Set<String> infinity,
  Set<String> nan,
  char zeroDigit
) {}
```

**Comment by Jolanrensen** [comment]
That looks promising!
>Do we need to support currency symbols? - I am leaving them out for now.

We probably need it so we can ignore it if it's there. We're parsing doubles from CSVs, so monetary values are common. Though, we don't currently support saving the currency type along with the numeric value, so if `"§5,12"` could be parsed as `5.12`, that would be good. (More generally, could it ignore unknown characters? or does that make it way more difficult?)

>Do all decimal digit sets in Unicode start with a zero character followed by the digits 1 to 9?
If yes, we can easily support multiple digit sets. All we need to know is the code point of the zero character.

Not entirely sure, but I think it's okay to just support digit sets that do for now. Arabic digits would be fine for instance :)

I think the grammar looks good and the record would be a great solution :) Though, it may be an ordered set. That way we could include "fallback" supported characters, such as the _normal_ "-" instead of the Estonian "−". It would come with some constraints of course, like we cannot fall back to using "," for the grouping separator if it's already used as decimal separator in the given locale, but that's an implementation detail, not something the parser should have to worry about.

**Comment by pjfanning** [comment]
Using a `record` means losing support for Java 8 and 11. If you go this route, would it be possible to continue to make bug fix releases for Java 8 and 11 users? I'm thinking in terms of jackson-core usage of this lib.

**Comment by wrandelshofer** [comment]
> More generally, could it ignore unknown characters? or does that make it way more difficult?

What do you mean by 'unknown character`? 🤔
Is an unknown character, a character that is not in `NumberFormatSymbols`, or may it occur as part of one of Strings (the infinity Strings, the nan Strings, the currency Strings)?

In the former case, we can skip them, 
in the latter case, we may have to use dynamic programming of some sorts.

**Comment by wrandelshofer** [comment]
> Using a `record` means losing support for Java 8 and 11. If you go this route, would it be possible to continue to make bug fix releases for Java 8 and 11 users? I'm thinking in terms of jackson-core usage of this lib.

No worrys. We are just prototyping here. 😉

**Comment by wrandelshofer** [comment]
> That way we could include "fallback" supported characters, such as the _normal_ "-" instead of the Estonian "−". It would come with some constraints of course, like we cannot fall back to using "," for the grouping separator if it's already used as decimal separator in the given locale, but that's an implementation detail, not something the parser should have to worry about.

Fallback is implemented best outside of this library. For a fallback, we have to start parsing all over again anyway.

**Comment by wrandelshofer** [comment]
> in the latter case, we may have to use dynamic programming of some sorts.

I think dynamic programming would still create surprising results.

Lets say we have an input with the following data:

```
1e2e3
```
Should the first 'e' be considered an unknown character, or the second 'e' or both?

**Comment by Jolanrensen** [comment]
@wrandelshofer I'd keep it simple and say an "unknown character" is simply one not in the number format symbols. This could be a monetary symbol, a non-standard grouping symbol or something like that. If we're sure it will not influence the numeric result, we should be able to ignore it. If it's an ambiguous case like multiple "e"'s then it's okay to throw an Exception.

**Comment by wrandelshofer** [comment]
Okay. I came up with something that you can use - hopefully - and that is not horribly slow.

I was not able to implement code that supports "unknown characters". It would have messed up the algorithm.

The code is in the branch [LenientDoubleParser](https://github.com/wrandelshofer/FastDoubleParser/tree/LenientDoubleParser).

The API is in class [LenientDoubleParser](https://github.com/wrandelshofer/FastDoubleParser/blob/f901f42bb04f80aefda71092c583e8b427c1b386/fastdoubleparser-dev/src/main/java/ch.randelshofer.fastdoubleparser/ch/randelshofer/fastdoubleparser/LenientDoubleParser.java)

The number format symbols can be specified in record [NumberFormatSymbols](https://github.com/wrandelshofer/FastDoubleParser/blob/f901f42bb04f80aefda71092c583e8b427c1b386/fastdoubleparser-dev/src/main/java/ch.randelshofer.fastdoubleparser/ch/randelshofer/fastdoubleparser/NumberFormatSymbols.java)


The syntax is a sub-set of the draft grammar that I have posted earlier:
- The sign can only be at the beginning of the input
- Grouping separators are supported

I made a test file with the Swiss-German locale [formatted_de-CH.txt](https://github.com/wrandelshofer/FastDoubleParser/blob/f901f42bb04f80aefda71092c583e8b427c1b386/fastdoubleparserdemo/data/formatted_de-CH.txt)

The input looks like this:

```
137’494’057.316
2’072.298
422’965’264.778
1’915’956.089
568’425’383.068
```

Here are the performance measurements:

```
File: formatted_de-CH.txt

CPU: Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
OS: Mac OS X, 15.0.1, 12 processors available
VM: Java 22, OpenJDK 64-Bit Server VM, Azul Systems, Inc., 22.0.2+9
-XX:CompileCommand=inline,java/lang/String.charAt

Measurement results:
|Method                     | MB/s  |stdev|Mfloats/s| ns/f   | speedup | JDK    |
|---------------------------|------:|-----:|------:|--------:|--------:|--------|
|java.text.NumberFormat     |  61.09| 3.9 %|   4.78|   209.12|     1.00|22.0.2  |
|LenientDoubleParser String | 313.88|13.3 %|  24.57|    40.70|     5.14|22.0.2  |
```

And here is a test run with the file [canada.txt](https://github.com/wrandelshofer/FastDoubleParser/blob/f901f42bb04f80aefda71092c583e8b427c1b386/fastdoubleparserdemo/data/canada.txt)

The input looks like this:
```
-65.613616999999977
43.420273000000009
-65.619720000000029
43.418052999999986
-65.625
```

```
File: canada.txt

Measurement results:
|Method                     | MB/s  |stdev|Mfloats/s| ns/f   | speedup | JDK    |
|---------------------------|------:|-----:|------:|--------:|--------:|--------|
|java.lang.Double           |  82.00| 4.7 %|   4.71|   212.21|     1.00|22.0.2  |
|java.text.NumberFormat     |  47.43| 4.4 %|   2.73|   366.89|     1.00|22.0.2  |
|JavaDoubleParser String    | 386.57| 7.9 %|  22.21|    45.01|     4.71|22.0.2  |
|LenientDoubleParser String | 348.00| 7.2 %|  20.00|    50.00|     7.34|22.0.2  |
```

I made the measurements on the following system:

```
CPU: Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
OS: Mac OS X, 15.0.1, 12 processors available
VM: Java 22, OpenJDK 64-Bit Server VM, Azul Systems, Inc., 22.0.2+9
-XX:CompileCommand=inline,java/lang/String.charAt

```

**Comment by wrandelshofer** [comment]
Ups, I accidentally deleted my comment, because it was showing twice. 😝

**Comment by wrandelshofer** [comment]
So, writing my post again. But shorter.

I made an experimental implementation on the branch named "LenientDoubleParser".

The API is in the class [LenientDoubleParser](https://github.com/wrandelshofer/FastDoubleParser/blob/f901f42bb04f80aefda71092c583e8b427c1b386/fastdoubleparser-dev/src/main/java/ch.randelshofer.fastdoubleparser/ch/randelshofer/fastdoubleparser/LenientDoubleParser.java).

It allows to configure the number format symbols using the record [NumberFormatSymbols](https://github.com/wrandelshofer/FastDoubleParser/blob/f901f42bb04f80aefda71092c583e8b427c1b386/fastdoubleparser-dev/src/main/java/ch.randelshofer.fastdoubleparser/ch/randelshofer/fastdoubleparser/NumberFormatSymbols.java).

This code does not allow for "unknown characters" in the input data.

I was not able to come up with an algorithm that allows for "unknown characters",
without resorting to dynamic programming and ruining the performance.


File: [formatted_de-CH.txt](https://github.com/wrandelshofer/FastDoubleParser/blob/f901f42bb04f80aefda71092c583e8b427c1b386/fastdoubleparserdemo/data/formatted_de-CH.txt)

```
12’961’872.332
-156’789’257.65
374’809’823.378
86’458’466.403
```


```
Measurement results:
|Method                     | MB/s  |stdev|Mfloats/s| ns/f   | speedup | JDK    |
|---------------------------|------:|-----:|------:|--------:|--------:|--------|
|java.text.NumberFormat     |  61.09| 3.9 %|   4.78|   209.12|     1.00|22.0.2  |
|LenientDoubleParser String | 313.88|13.3 %|  24.57|    40.70|     5.14|22.0.2  |
```


File: [canada.txt](https://github.com/wrandelshofer/FastDoubleParser/blob/f901f42bb04f80aefda71092c583e8b427c1b386/fastdoubleparserdemo/data/canada.txt)

```
-65.613616999999977
43.420273000000009
-65.619720000000029
43.418052999999986
-65.625
```


```
Measurement results:
|Method                     | MB/s  |stdev|Mfloats/s| ns/f   | speedup | JDK    |
|---------------------------|------:|-----:|------:|--------:|--------:|--------|
|java.lang.Double           |  82.00| 4.7 %|   4.71|   212.21|     1.00|22.0.2  |
|java.text.NumberFormat     |  47.43| 4.4 %|   2.73|   366.89|     1.00|22.0.2  |
|JavaDoubleParser String    | 386.57| 7.9 %|  22.21|    45.01|     4.71|22.0.2  |
|LenientDoubleParser String | 348.00| 7.2 %|  20.00|    50.00|     7.34|22.0.2  |
```

**Comment by wrandelshofer** [comment]
I have renamed `LenientDoubleParser` to `ConfigurableDoubleParser`.

**Comment by wrandelshofer** [comment]
I have it merged into the main branch.

**Comment by Jolanrensen** [comment]
Do you have a dev version released so I can test it more easily in our project?

**Comment by wrandelshofer** [comment]
I have now made the following release:
https://github.com/wrandelshofer/FastDoubleParser/releases/tag/2024-10-13_c95fc915

**Comment by Jolanrensen** [comment]
@wrandelshofer I've been testing it for some of our cases and it seems like it works quite well :). There are just some small things I found:

I wasn't able to parse "1,234e3" at first, because the exponent character is 'E' by default. Adding 'e' manually worked. I had to do the same for "NaN" (and "NAN", "nan", etc.). Could we have an option to ignore cases?

 It seems the minus symbols don't work. I added both the estonian and normal minus sign to the set, but it seems to fail. To reproduce it, here's my function (forgive my Kotlin):
 
 ```kt
 @Test
fun temp() {
    val estonianMinus = "−13,35"
    val ordinaryMinus = "-13,35"

    val dfs = DecimalFormatSymbols.getInstance(
        Locale.forLanguageTag("et-EE"),
    )

    assert(dfs.minusSign == '−') { "Expected estonian minus sign '−' but got '${dfs.minusSign}'" }
    val parser = ConfigurableDoubleParser(
        NumberFormatSymbols(
            setOf(dfs.decimalSeparator),
            setOf(dfs.groupingSeparator),
            setOf(dfs.exponentSeparator),
            setOf(dfs.minusSign, '-'), // adding estonian minus sign and normal one
            setOf('+'),
            setOf(dfs.infinity),
            setOf(dfs.naN),
            dfs.zeroDigit,
        ),
    )

    parser.parseDouble(ordinaryMinus) // works
    parser.parseDouble(estonianMinus) // fails
}
 ```

**Comment by wrandelshofer** [comment]
Thank you for testing! 🙂

I have now added a boolean parameter `ignoreCase` to the constructor of `ConfigurableDoubleParser`.

I made fixes for the sign characters.

Here is a new snapshot release:
https://github.com/wrandelshofer/FastDoubleParser/releases/tag/2024-10-13_199e49bf


I haven't started yet with the byte array support. 
This is more work, because we will need two implementations: One for the ISO-8859-1 case, and one for the UTF-8 case.

**Comment by Jolanrensen** [comment]
@wrandelshofer Thank you very much :D It seems to pass all our test cases!

I programmed the fallback-mechanism on our side such that each NumberFormatSymbol based on the given locale gets a NFS from the ROOT locale only if that fallback character/string does not already appear in the NFSs of the given locale. 

That way locales with different minus signs can also use the normal "-", and locales with NBSP as grouping symbol can use both "," and "." as decimal separator. Very forgiving :)

Plus some extra notations for "infinity" for good measure :).

**Comment by wrandelshofer** [comment]
@Jolanrensen This is great. 😀

Next, I am going to implement better slow paths for the parsers. 
In the slow path, we currently creates a new locale-independent String, and pass it to Double.parseDouble().
There is a better way to do this.

**Comment by wrandelshofer** [comment]
I need to revisit the API. 

The current API does not support digits that do not have consecutive code points from 0 to 9 in Unicode.
For example, with the current API, we cannot parse the following String produced with JavaScript:

```JavaScript
new Intl.NumberFormat("zh-Hans-CN-u-nu-hanidec").format(9876543210)
```

`"九,八七六,五四三,二一〇"`

**Comment by wrandelshofer** [comment]
I made a new [snapshot release](https://github.com/wrandelshofer/FastDoubleParser/releases/tag/2024-10-20_114324cc).

This release adds support for digits on non-consecutive code points and for byte arrays.

Parsing of byte arrays is considerably slower than parsing char arrays.
This is because a char in the UTF-8 encoding has a variable length of 1 to 4 bytes.

Parsing a byte array is supposed to be faster than converting the byte array to a String and then parsing the String.

**Comment by wrandelshofer** [comment]
Here are some performance measurements. In the tables below, "CI" stands for case-insensitive.

**English Locale**
Locale `en-GB` with rows looking like `6,459,718.479`, `2.208705672430846E7`.
This is a fast case. A digit is encoded by 1 byte in UTF-8.

Measurement results:
|Method                                   | MB/s  |stdev|Mfloats/s| ns/f   | speedup | JDK    |
|-----------------------------------------|------:|-----:|------:|--------:|--------:|--------|
|java.text.NumberFormat                   |  50.24|11.0 %|   3.72|   268.90|   1.00=a|23      |
|com.ibm.icu.text.NumberFormat            |  20.39| 4.2 %|   1.51|   662.68|   1.00=b|23      |
|ConfigurableDoubleParser CharSequence    | 210.77|12.2 %|  15.60|    64.10|   4.20*a|23      |
|ConfigurableDoubleParser char[]          | 312.41|11.7 %|  23.13|    43.24|   6.22*a|23      |
|ConfigurableDoubleParser byte[]          | 310.99|21.8 %|  23.02|    43.44|   6.19*a|23      |
|ConfigurableDoubleParserCI CharSequence  | 216.98| 8.7 %|  16.06|    62.26|   4.32*a|23      |
|ConfigurableDoubleParserCI char[]        | 297.13|10.5 %|  21.99|    45.47|   5.91*a|23      |
|ConfigurableDoubleParserCI byte[]        | 295.63|20.5 %|  21.88|    45.70|   5.88*a|23      |

**Arabian Locale**
Locale `ar` with rows looking like `١٨٫٨٥٦`, `٢٤١٦٥٢٨٫٣٤٥٧٨٣٨٢٩أس٠`.
This is a slow case. A digit is encoded by 2 bytes in UTF-8.

Measurement results:
|Method                                   | MB/s  |stdev|Mfloats/s| ns/f   | speedup | JDK    |
|-----------------------------------------|------:|-----:|------:|--------:|--------:|--------|
|java.text.NumberFormat                   |  58.55| 7.3 %|   4.15|   241.03|   1.00=a|23      |
|com.ibm.icu.text.NumberFormat            |  19.92|14.0 %|   1.41|   708.45|   1.00=b|23      |
|ConfigurableDoubleParser CharSequence    | 222.77|13.1 %|  15.78|    63.36|   3.80*a|23      |
|ConfigurableDoubleParser char[]          | 240.60| 9.8 %|  17.05|    58.66|   4.11*a|23      |
|ConfigurableDoubleParser byte[]          | 139.07|16.9 %|   9.85|   101.49|   2.37*a|23      |
|ConfigurableDoubleParserCI CharSequence  | 211.44|14.8 %|  14.98|    66.75|   3.61*a|23      |
|ConfigurableDoubleParserCI char[]        | 240.15| 9.6 %|  17.02|    58.77|   4.10*a|23      |
|ConfigurableDoubleParserCI byte[]        | 140.98| 7.2 %|   9.99|   100.11|   2.41*a|23      |

**Chinese Locale**
Locale `zh-CN` with rows looking like `二一,七二七,二七九.二八九`, `四一.五七五三七一六六二一四五九八*一〇^七`.
This is another slow case. A digit is encoded by 4 bytes in UTF-8.

Measurement results:
|Method                                   | MB/s  |stdev|Mfloats/s| ns/f   | speedup | JDK    |
|-----------------------------------------|------:|-----:|------:|--------:|--------:|--------|
|com.ibm.icu.text.NumberFormat            |   9.64|10.4 %|   0.69|  1442.38|   1.00=a|23      |
|ConfigurableDoubleParser CharSequence    | 181.47|15.2 %|  13.06|    76.59|  18.83*a|23      |
|ConfigurableDoubleParser char[]          | 221.19| 8.6 %|  15.91|    62.84|  22.95*a|23      |
|ConfigurableDoubleParser byte[]          | 121.58| 7.6 %|   8.75|   114.32|  12.62*a|23      |
|ConfigurableDoubleParserCI CharSequence  | 189.60| 9.7 %|  13.64|    73.30|  19.68*a|23      |
|ConfigurableDoubleParserCI char[]        | 205.83|14.0 %|  14.81|    67.52|  21.36*a|23      |
|ConfigurableDoubleParserCI byte[]        | 106.89|19.0 %|   7.69|   130.02|  11.09*a|23      |

**Comment by wrandelshofer** [comment]
I have added `with`-methods to `NumberFormatSymbols`. This makes customisation easier.

```java
var symbols = NumberFormatSymbols.fromDecimalFormatSymbols(
                             new DecimalFormatSymbols(Locale.forLanguageTag("zh-CN")));
symbols = symbols
                .withDigits(List.of('〇', '一', '二', '三', '四', '五', '六', '七', '八', '九'))
                .withExponentSeparator((Set.of("*一〇^")));

```

**Comment by Jolanrensen** [comment]
thanks for your awesome work :)

**Comment by wrandelshofer** [comment]
Hm, I think, the library should also provide a ConfigurableBigDecimalParser. 🤔

**Comment by Jolanrensen** [comment]
> Hm, I think, the library should also provide a ConfigurableBigDecimalParser. 🤔

If you can, we would probably also use it :)

**Comment by Jolanrensen** [comment]
I was wondering, would it be possible to also publish a (dev/snapshot/preview) version to maven central? It's okay if it's an experimental version like in the release jar on GH, but it could make it easier to ship it as part our library as experimental new feature.

**Comment by wrandelshofer** [comment]
I have published this as version 2.0.0 on [central.sonatype.com](https://central.sonatype.com/artifact/ch.randelshofer/fastdoubleparser).

Apparently, I can not publish versions that deviate from x.y.z numbering scheme on sonatype.

**Comment by Jolanrensen** [comment]
Awesome :D thanks! Ah I see, you could consider publishing dev versions to GitHub packages instead. It's what we do with dev versions of our library

**Comment by wrandelshofer** [comment]
Oh, I didn't know about GitHub packages. I am going to try this out in the future. 😀

**Comment by wrandelshofer** [comment]
@lemire Ah, very nice, I can use your project as a template! 😀

**Comment by lemire** [comment]
@wrandelshofer

Have a look at our release.yml workflow. That's where the magic happens. We use gradle and not maven, but it should be very similar.

 See...

https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-java-packages-with-gradle#publishing-packages-to-github-packages


I recommend support GitHub packages as it gives people options. It ties the artefacts to your GitHub releases... so they can always find the releases, no matter what.

For JitPack, it is entirely automated... but you seem to have hit problems...

See the log...

https://jitpack.io/com/github/wrandelshofer/FastDoubleParser/2024-10-20_114324cc/build.log

I really like JitPack because it just works. See 

https://github.com/RoaringBitmap/RoaringBitmap?tab=readme-ov-file#usage-within-a-maven-project

for how users can consume the library. It is really easy and convenient.

**Comment by Jolanrensen** [comment]
I think we can close this one for now, as our issues have all been resolved :) Thanks again for the awesome work!

**Comment by Jolanrensen** [comment]
@wrandelshofer I actually found another bug, this time parsing from `Locale("fi")`. They use `exponentSeparator='e'`, and `nan="epäluku"`, which I suspect clashes.

**Comment by Jolanrensen** [comment]
There's also an interesting case with RTL languages, like `Locale("ar")`. At least on Java 8, the minus sign is represented by `[28, 6]`, or `'\u061c'`. This is probably not 100% correct from Java's side, as this is simply the [Arabic letter mark](https://en.wikipedia.org/wiki/Arabic_letter_mark), not actually the minus sign. This can also be seen when you format a negative double to an Arabic String. No minus sign is visible. Still, `NumberFormatter` catches this character and interprets it as minus.
However, when I try to do the same with `ConfigurableDoubleParser`, it fails because this "minus sign" is recognized as a FORMAT character and is thus skipped when parsing it. Maybe we could check whether any of the provided characters is actually a format symbol and not skip it if that is the case?

**Comment by wrandelshofer** [comment]
> For JitPack, it is entirely automated... but you seem to have hit problems...
> 
> See the log...
> 
> https://jitpack.io/com/github/wrandelshofer/FastDoubleParser/2024-10-20_114324cc/build.log

Apparently they try to build the code with an older version of Maven. This is unfortunate, because I want to move to Maven 4.0.0 as soon as it gets out of beta. (The current version of Maven does not support repeatable builds with Java 23).

**Comment by wrandelshofer** [comment]
> There's also an interesting case with RTL languages, like `Locale("ar")`. At least on Java 8, the minus sign is represented by `[28, 6]`, or `'\u061c'`. This is probably not 100% correct from Java's side, as this is simply the [Arabic letter mark](https://en.wikipedia.org/wiki/Arabic_letter_mark), not actually the minus sign. This can also be seen when you format a negative double to an Arabic String. No minus sign is visible. Still, `NumberFormatter` catches this character and interprets it as minus. However, when I try to do the same with `ConfigurableDoubleParser`, it fails because this "minus sign" is recognized as a FORMAT character and is thus skipped when parsing it. Maybe we could check whether any of the provided characters is actually a format symbol and not skip it if that is the case?

I can not produce numbers with just '\u061c' as the minus sign with DecimalFormat on Java 8. Can you provide a code snippet that produces them?

```java
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;

public final class DecimalFormatMain {

    public static void main(String... args) throws IOException, ParseException {
        Locale locale = Locale.forLanguageTag("ar");
        DecimalFormat f = (DecimalFormat) NumberFormat.getNumberInstance(locale);
        String formatted = f.format(-123_456.789);
        System.out.println(formatted);
        for (char ch:formatted.toCharArray()){
            System.out.print("U+"+Integer.toHexString(ch)+" ");
        }
        System.out.println();
    }
}
```

With Java 8 we get `123,456.789-`  U+31 U+32 U+33 U+2c U+34 U+35 U+36 U+2e U+37 U+38 U+39 U+2d.
With Java 23 we get `؜-١٢٣٬٤٥٦٫٧٨٩` U+61c U+2d U+661 U+662 U+663 U+66c U+664 U+665 U+666 U+66b U+667 U+668 U+669 . 

ConfigurableDoubleParser can not parse the output from Java 8, because the '-' character is at the end. I think, I should add support for this. (I mentioned earlier that I want to do it, but I hesitated). It looks like DecimalFormat can parse a minus sign at the end just fine.🤔

Since you need to be able to define a format character as a sign symbol, you might also have the be able to define a non-format character as a format character? 🤔

**Comment by lemire** [comment]
@wrandelshofer 

Their documentation states that you can specify the maven version with a wrapper.


![IMG_6606](https://github.com/user-attachments/assets/0dd10ecf-a6fe-496f-85d1-b8b061759bfe)

**Comment by Jolanrensen** [comment]
@wrandelshofer Hmm it's strange, whether the minus shows up at all depends on which console/environment I use. If I print it from a JUnit test it does not show up with your example, but from a Kotlin Notebook (JVM 17) it does...

Where I find the '\u061C' character is actually in `f.getDecimalFormatSymbols().getMinusSign()`, which I use to configure `NumberFormatSymbols`.

Also, if I retrieve the result from `f.format(1.0)` I get "U+661", but calling `f.format(-1.0)` gives me "U+61c, U+661", so no minus, just the arabic letter symbol.

Could you also check Java 11? I have a suspicion my debugger secretly uses 11 instead of 8.

**Comment by wrandelshofer** [comment]
Yes, you are right. It is Java 11 that uses U+61c for the sign character.

With Java 11 we get `؜١٢٣٬٤٥٦٫٧٨٩`
U+61c U+661 U+662 U+663 U+66c U+664 U+665 U+666 U+66b U+667 U+668 U+669

**Comment by wrandelshofer** [comment]
Does anyone actually use Java 11 for generating CSV files with the arabic script? 
I mean, the output looks wrong to everybody who inspects it visually. 🧐
And - I guess - nobody can parse this correctly except with a Java 11 VM.

**Comment by Jolanrensen** [comment]
thanks again :D
