### ISSUE TITLE
Under zing24, double parsing returns an abnormal value.

### ISSUE THREAD

**Issue by HaoClassmate** [wrandelshofer/FastDoubleParser#83]
environment：openjdk version "21.0.4" 2024-09-27 LTS
OpenJDK Runtime Environment Zing24.09.0.0+5 (build 21.0.4+4-LTS)
Zing 64-Bit Tiered VM Zing24.09.0.0+5 (build 21.0.4-zing_24.09.0.0-b5-release-linux-X86_64, mixed mode)

 ` 

    public static void main(String[] args) {
        for (int i = 0; i < 100000000; i++) {
            double doubleValue = JavaDoubleParser.parseDouble("6.2810452735993785");
            if (doubleValue > 7) {
                System.out.println("doubleValue = " + doubleValue);
            }
        }
    }
`
    print:
doubleValue = 9.124181094397514
doubleValue = 9.124181094397514

**Comment by wrandelshofer** [comment]
Can you reproduce the problem in the interpreter mode of the JVM? With option `-Xint`

**Comment by HaoClassmate** [comment]
The problem cannot be reproduced in the interpreter mode of the JVM,
Under zing24, Double.parseDouble also works as expected.
It is also normal under the java version “21.0.1” 2023-10-17 LTS.

**Comment by wrandelshofer** [comment]
You should report this as a bug in the JIT to the Zing JVM.

**Comment by HaoClassmate** [comment]
The problem was also reproduced in openJdk21, and it was found that only lengths greater than 18 would be parsed as incorrect data after jit optimization.

java version "21.0.3" 2024-04-16 LTS
Java(TM) SE Runtime Environment (build 21.0.3+7-LTS-152)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.3+7-LTS-152, mixed mode, sharing)

`
    public static void main(String[] args) {
        for (int i = 0; i < 100000000; i++) {
            double value = 3044.07953904259;
            double doubleValue = JavaDoubleParser.parseDouble("1785.0198847606475");
            if (doubleValue != value) {
                System.out.println("i:"+i + ",doubleValue:" + doubleValue);
            }
        }
    }
`
print:
i:8660634,doubleValue:1785.0198847606475
i:8660635,doubleValue:1785.0198847606475
i:8660636,doubleValue:1785.0198847606475
i:8660637,doubleValue:1785.0198847606475
i:8660638,doubleValue:1785.0198847606475
i:8660639,doubleValue:1785.0198847606475
i:8660640,doubleValue:1785.0198847606475

**Comment by wrandelshofer** [comment]
Maybe `java.lang.Math.unsignedMultiplyHigh(long,long)` is the problem?

I have copied the relevant code into a single source file. 

I have attached it as a .zip file, because githut does not let me attach a .java file. 

Can you reproduce the problem with this file?

If yes, then replace the code of the method unsignedMultiplyHigh with this code:

```java
    static long unsignedMultiplyHigh(long x, long y) {//before Java 18
        long x0 = x & 0xffffffffL, x1 = x >>> 32;
        long y0 = y & 0xffffffffL, y1 = y >>> 32;
        long p11 = x1 * y1, p01 = x0 * y1;
        long p10 = x1 * y0, p00 = x0 * y0;

        // 64-bit product + two 32-bit values
        long middle = p10 + (p00 >>> 32) + (p01 & 0xffffffffL);

        // 64-bit product + two 32-bit values
        return p11 + (middle >>> 32) + (p01 >>> 32);
    }
```

[ZingAbnormalMain.java.zip](https://github.com/user-attachments/files/17510525/ZingAbnormalMain.java.zip)

**Comment by HaoClassmate** [comment]
It's true that unsignedMultiplyHigh is causing the problem, I replaced the unsignedMultiplyHigh code you provided and it runs fine!

**Comment by lemire** [comment]
Intriguing. What is your processor? ARM or x64?

**Comment by HaoClassmate** [comment]
Kernel: Linux 5.10.134-16.3.al8.x86_64
Architecture: x86-64

**Comment by wrandelshofer** [comment]
I have made a shorter version here. Can you please try if it still reproduces the bug, and then report it to the Zing team? 

Do you need a patched version of the FastDoubleParser library that does not call `Math.unsignedMultiplyHigh`?


[ReproduceZingMain.java.zip](https://github.com/user-attachments/files/17519051/ReproduceZingMain.java.zip)

**Comment by wrandelshofer** [comment]
I have published a workaround as version 1.0.90 on [central.sonatype.com](https://central.sonatype.com/artifact/ch.randelshofer/fastdoubleparser).

**Comment by HaoClassmate** [comment]
Ok, thanks, version 1.0.90 works fine!

**Comment by pjfanning** [comment]
@HaoClassmate can you link the Zing issue?
